optic/urls.py
from django.urls import path

from . import views

app_name = 'optic'

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
]

weboptic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('optic.urls')),
    path('admin/', admin.site.urls),
]

optic/models.py
from django.db import models

# Create your models here.

optic/views.py
from django.shortcuts import render
from library.search_engine.SearchEngine import SearchEngine


def index(request):
    return render(request, 'optic/index.html')


def search(request):
    q = request.GET.get('query', None)
    searchEngine = SearchEngine(q)
    data = searchEngine.searchResults
    return render(request, 'optic/results.html', {'data': data, 'query': q})

optic/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body class="bg-light">
    {% block content %}

    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

optic/templates/optic/index.html
{% extends 'layout.html' %}

{% block content %}
       <div class="container">
            <div class="p-5 text-center">
                <form class="wrap" action="{% url 'optic:search' %}" method="get" style="display: inline-block">
                    {% csrf_token %}
                   <div class="search d-flex">
                      <input type="text" name="query" class="form-control bg-white" placeholder="" autofocus>
                       <button type="submit" class="btn btn-primary ml-1">Search</button>
                   </div>
                </form>
            </div>
       </div>

{% endblock content %}

optic/templates/optic/results.html
{% extends 'layout.html' %}
{% load static %}


{% block content %}
    <div class="p-5 text-center">
        <form class="wrap" action="{% url 'optic:search' %}" method="get" style="display: inline-block">
            {% csrf_token %}
           <div class="search d-flex">
              <input type="text" name="query" class="form-control bg-white" value="{{ query }}" autofocus>
               <button type="submit" class="btn btn-primary ml-1">Search</button>
           </div>
        </form>
    </div>

   <div class="container mb-3" style="width: 50%; margin: auto">
        {% for searchResult in data %}
            <div class="bg-white mt-3 rounded p-3">
                <h5 class="text-primary">{{ searchResult.title }}</h5>
                <p>
                    <a class="text-success" href="{{ searchResult.link }}">{{ searchResult.link }}</a>
                </p>
                <p class="text-dark">
                    {{ searchResult.extract }}
                </p>
            </div>
        {% endfor %}
   </div>


{% endblock content %}